### ISSUE TITLE
Allow for a looser range of runtime dependency versions in conformance with semver backward compatibility guarantees

### ISSUE THREAD

**Issue by discosultan** [bunq/sdk_python#107]
Current dependencies for the SDK are defined as follows:

```py
# Run-time dependencies of the project. These will be installed by pip.
install_requires = [
    'aenum==2.0.8',
    'chardet==3.0.4',
    'pycryptodomex==3.4.6',
    'requests==2.18.1',
    'simplejson==3.11.1',
    'urllib3==1.21.1'
]
```

This locks consumers into those particular versions of vendor libs preventing from applying minor and patch updates.

In order to allow for more flexibility but ensure compatibility (as stated by [semver](https://semver.org/#summary)) with vendor libs, the dependencies could be defined within major version ranges instead:

```py
# Run-time dependencies of the project. These will be installed by pip.
install_requires = [
    'aenum>=2.0.8,<3.0.0',
    'chardet>=3.0.4,<4.0.0',
    'pycryptodomex>=3.4.6,<4.0.0',
    'requests>=2.18.1,<3.0.0',
    'simplejson==3.11.1,<4.0.0',
    'urllib3>=1.21.1,<2.0.0'
]
```

**Comment by angelomelonas** [comment]
Hi @discosultan 👋🏼 

Sorry for the very late response. Thanks for the suggestion 🙏🏼 It will be included in the following release! We have also since updated all dependencies to their latest (minor) versions.
