### ISSUE TITLE
Break the SDK's dependence on the bunq.conf file

### ISSUE THREAD

**Issue by PJUllrich** [bunq/sdk_python#11]
It would be nice to have the option to save the API parameters to e.g. a database instead of to the `bunq.conf` file. For now, one can download the code and rewrite the saving function, or mock the saving function, either possibility is not very desirable.

**Comment by OGKevin** [comment]
Hey @PJUllrich, 

This has been requested and is on our "wishlist" 😬, however I don't have an ETA at the moment but will keep you posted 👍.

**Comment by OGKevin** [comment]
This has been fixed in #13
