### ISSUE TITLE
The CHANGELOG is out of date

### ISSUE THREAD

**Issue by haarts** [bunq/sdk_python#131]
## Steps to reproduce:
1. Look at CHANGELOG.md, observe it end at a 1.10 release. 

## What should happen:
1. It should contain the 1.13 release

## What happens:
1. The `tinker_python` repo floats the dependency of this SDK, this is unwise and breaks now. I headed over to this repo to see what changed and found a stale changelog. :disappointed: 

## SDK version and environment
- Tested on [1.13.1](https://github.com/bunq/sdk_python/releases/tag/1.13.1)
- [x ] Sandbox
- [ ] Production

Python 3.7, Ubuntu 19.10

**Comment by siccovansas** [comment]
This is a shame as it makes developing using Bunq's SDK quite a bit more difficult.
