### ISSUE TITLE
Missing a callback sample

### ISSUE THREAD

**Issue by CharlPels** [bunq/sdk_python#15]
Is it possible to ad a callback code sample.
The webserver i can configure my self etc but love to have a sample on how to setup the callback so for example when a pin or other transaction happens i can react on it.

Not an issue just a request :-)

**Comment by OGKevin** [comment]
Hey @CharlPels 

Here an example to set a call back to UserPerson 👍 

```python

from bunq.sdk.model.generated.endpoint import UserPerson
from bunq.sdk.model.generated.object_ import NotificationFilter
from bunq.sdk.context import ApiContext

ctx = ApiContext.restore()
USER_ID = 400

filter_ = NotificationFilter('URL', 'myurl.com', 'BILLING')

request_body = {
    UserPerson.FIELD_NOTIFICATION_FILTERS: filter_
}

UserPerson.update(ctx, request_body, USER_ID)
```
Let me know if this is what you were looking for 😄.

**Comment by CharlPels** [comment]
No luck, get an error
bunq.sdk.exception.ApiException: HTTP Response Code: 400
Invalid type for field "notification_filters" (expected ARRAY containing STRUCT).

filter i use is
filter_ = NotificationFilter('URL', 'https://<azure function>.azurewebsites.net/<functionwebhook>', 'BILLING')

**Comment by dnl-blkv** [comment]
@OGKevin @CharlPels 
I believe it should have been:
```
from bunq.sdk.model.generated.endpoint import UserPerson
from bunq.sdk.model.generated.object_ import NotificationFilter
from bunq.sdk.context import ApiContext

ctx = ApiContext.restore()
USER_ID = 400

filters = [NotificationFilter('URL', 'myurl.com', 'BILLING')]

request_body = {
    UserPerson.FIELD_NOTIFICATION_FILTERS: filters
}

UserPerson.update(ctx, request_body, USER_ID)
```

Source: https://doc.bunq.com/api/1/call/user-person/method/put

@CharlPels please let me know if this doesn't work. I did not run the code myself yet - will do so as the first thing tomorrow, if it still doesn't work :)

**Comment by OGKevin** [comment]
@CharlPels 😁 I forgot to array it indeed @dnl-blkv example looks about right 😉

**Comment by CharlPels** [comment]
The [] did the trick as in there are no erros anymore however i don't see anything coming in :-(
Also I have no clue on how to see the configuration was a succes or how to remove a callback endpoint

**Comment by OGKevin** [comment]
@CharlPels To remove a callback you can do this: 
```
filters = [NotificationFilter('PUSH', None, 'BILLING')]
```
https://together.bunq.com/topic/unregister-callback-webhook#comment-7926

```
UserPerson.update(ctx, request_body, USER_ID)
```
Will return an id as shows here: https://doc.bunq.com/api/1/call/user-company/method/put

If you get this id, means that the request came back with status 200 (which means everything went successful)

Afterwards depending on the category you've chosen, which are listed here: https://doc.bunq.com/api/1/page/callbacks

You will get a POST request to the url you defined.

**Comment by OGKevin** [comment]
Closing the issue, feel free to comment afterwards.
