### ISSUE TITLE
Extract JsonAdapter as own library

### ISSUE THREAD

**Issue by PJUllrich** [bunq/sdk_python#3]
Your functionality on de- & serialising (especially **nested**) JSON data to Python classes is pretty neat and actually high in demand in the Python community at the moment. 

Until now, **JSONPickle** is mostly the library of choice when de/serialising nested JSON data from and to Python objects, but "pickled" JSON Data (with Pickle serialised Python Objects) can only be deserialised with the same methods as with which they were serialised. Therefore, nested JSON data received from somewhere else cannot be deserialised without knowing how it was serialised. 

Your JSONAdapter class seems to be able to do just that without knowing how the data was serialised. Given the need for such functionality in the Python community, I'd like to propose that you extract this functionality into a separate library and preferably put it on PyPi.

**Comment by OGKevin** [comment]
This is indeed a good and valid point 👍. We'll look into this and see if we can manage to achieve this in one of the next releases. But first we must get the whole SDK on PyPi first 😋.

**Comment by dnl-blkv** [comment]
@PJUllrich That's a great idea, thank you!

Our library, however, does know about the types of the data received: it reads those from the docstrings of the models.

So, basically it does know _which  object_ the data represents. The rest is just looping around the nested structure and reading the types of everything from docstrings of Python :)

**Comment by PJUllrich** [comment]
@dnl-blkv hmm that's a bummer indeed. Well a bummer because to have such functionality would be pretty awesome ;-) . However, it's also been a while since I looked into this de/serialization issue in Python. I'll do some research and come back to this.
