### ISSUE TITLE
Missing CARD GENERATED CVC2 endpoint 

### ISSUE THREAD

**Issue by OGKevin** [bunq/sdk_python#33]
## Steps to reproduce:
1. Take a look at the possible pub API endpoints 

## What should happen:
1. https://doc.bunq.com/api/1/call/card-generated-cvc2 is included in the SDK 

## What happens:
1. It is not included in the SDK 

## Extra info:
- Tested on https://github.com/bunq/sdk_python/tree/0.12.0

**Comment by dnl-blkv** [comment]
Merged
