### ISSUE TITLE
Add more example scripts

### ISSUE THREAD

**Issue by OGKevin** [bunq/sdk_python#68]
This issue is meant to keep track of the example scripts included in the SDK.

- [x] ApiContext
  - [x] Save/restore
  - [ ] Ensure that session is active
- [x] Attachments
- [ ] Callbacks
- [ ] Cards
  - [x] Order card
- [ ] Card payments
  - [ ] MasterCard action
- [ ] Cash registers
- [ ] Chat
- [ ] Connects
- [x] Export statements
- [ ] Invoices
- [ ] Monetary accounts
- [ ] Payment
  - [ ] Draft Payment
  - [ ] Scheduled Payment
  - [x] Payment batch
  - [x] Tab Payment
- [x] Request for payment / Request inquiry
- [x] User
  
  
  - bunq/sdk_php#98

**Comment by TimZ99** [comment]
What do you want as an example for Monetary accounts?

**Comment by OGKevin** [comment]
Hey @TimZ99 

I think an example on how to get all your monetary accounts and how to get one via the ID should be enough. But this issue is on hold as there is going to be a refactor of the SDK which might lead to changes to the methods and therefore making the examples obsolete. Ill update the issue once were ready to write all these examples.
