### ISSUE TITLE
Payment.list() pagination workaround

### ISSUE THREAD

**Issue by PJUllrich** [bunq/sdk_python#8]
I heard from @OGKevin that pagination of payment lists does not work yet, but I wanted to ask whether you maybe have a temporary workaround for that? 

I thought about maybe using the Payment ID, but I'm not sure whether that ID is specific per user (i.e. increases by 1 whenever the user makes a payment, independently of the actions of other users) or global (increases whenever any user makes a payment). 

Do you maybe have an idea of a workaround in mind?

**Comment by OGKevin** [comment]
Even if you manage to get the pagination url, there is no way to make a call to it via the SDK 🤔. So I think there is no other work around to just implement it right ? @dnl-blkv

**Comment by dnl-blkv** [comment]
@PJUllrich There is no quick workaround yet, but it will be there in the near future. Soon (today or tomorrow) we will release 0.10.0, which will include response object. On top of it, we will add pagination (included as a part of the response object).
