### ISSUE TITLE
bunq-sdk 0.12.4 package on PyPI contains code from 0.13.0

### ISSUE THREAD

**Issue by Ch00k** [bunq/sdk_python#88]
Apparently an error has been made while releasing 0.13.0 to PyPI, because the PyPI package with version 0.12.4 now contains code from 0.13.0. This basically breaks everything :(

**Comment by OGKevin** [comment]
Could you provide code to back this up as I could not find any trace of this. I just installed versions 0.12.4 from pip and looked the following line: https://github.com/bunq/sdk_python/blob/25c6e353dfcefedfd4e1cd01e6cea529c710e7ef/bunq/sdk/client.py#L53
As you can see on tag `0.13.0` it shows the correct version. While on the package `0.12.4`  installed via PIP it  shows 

```
tmp ⍉ ➜ PIPENV_VENV_IN_PROJECT=1 pipenv --python 3.6 install bunq-sdk==0.12.4
sdk ⍉ ➜ cat client.py | grep AGENT
    HEADER_USER_AGENT = 'User-Agent'
    _USER_AGENT_BUNQ = 'bunq-sdk-python/0.12.4'
            cls.HEADER_USER_AGENT: cls._USER_AGENT_BUNQ,
sdk ➜
```

So seeing that this is correct it seems highly unlikely that there will be other code thats not suppose to be there 🤔.

Unless im missing something. So please could you provide a code snippet that you think should not be there so I can further investigate.

**Comment by Ch00k** [comment]
Yeah, sorry for not being clear enough. Apparently, not the whole package code was updated. To reproduce:
1. Download `bunq_sdk-0.12.4-py3-none-any.whl` from [this](https://pypi.python.org/pypi/bunq-sdk/0.12.4) page.
2. Unzip the file
3. Look into the file `bunq/sdk/model/generated/endpoint.py` - it contains from [0.13.0](https://github.com/bunq/sdk_python/blob/0.13.0/bunq/sdk/model/generated/endpoint.py) instead of [0.12.4](https://github.com/bunq/sdk_python/blob/0.12.4/bunq/sdk/model/generated/endpoint.py)

**Comment by OGKevin** [comment]
😅 you're right. I have no idea how this is possible.  Sucks that pip doest just use GitHub like the other package managers 😔 

For now, I would suggest you to use pip to install directly from GitHub as explained [here](https://stackoverflow.com/questions/20101834/pip-install-from-git-repo-branch)

**Comment by OGKevin** [comment]
As I cant seem to override the package from pypi and also have no clue how it even got overwritten. I will host the .gz file on [GitHub release](https://github.com/bunq/sdk_python/releases/tag/0.12.4). 

You can build it locally your self running the following: 

```
$ git checkout 0.12.4
$ python setup.py sdist
$ cd dist/
```

in there you will find the build. 

Closing the issue for now.
