### ISSUE TITLE
Sample for reading/using shared accounts

### ISSUE THREAD

**Issue by CharlPels** [bunq/sdk_python#90]
## Steps to reproduce:
1. None

## What should happen:
1. Add some examples for shared accounts

## What happens:
1. Make customer happy

## Traceback
[//]: # (If there is a traceback please share it in a quote! You can do this by pasting the traceback text, highlighting it and pressing the quote button.)

## SDK version and environment
- Tested on [0.12.4](https://github.com/bunq/sdk_python/releases/tag/0.12.4)
- [ ] Sandbox
- [ ] Production

## Response id
[//]: # (If this error has something to do with a request that fails, please provide the response id of the request.)
- Response id:

## Extra info:
[//]: # (Please provide any other relevant information here)

**Comment by CharlPels** [comment]
Hello,

Sorry with shared accounts I mean joint accounts :-)
did an update of the bunq SDK, that seems to break my solution :-(
bunq.sdk.exception.BunqException: ApiContext has not been loaded. Please load ApiContext in BunqContext

no clue why :-(

**Comment by OGKevin** [comment]
You can use this as example: 

https://github.com/bunq/tinker_python/blob/3898543198df8c5a496fdb35dd70c994c556b102/tinker/libs/bunq_lib.py#L69-L73

For monetary account joint you can use: https://github.com/bunq/sdk_python/blob/25c6e353dfcefedfd4e1cd01e6cea529c710e7ef/bunq/sdk/model/generated/endpoint.py#L13476

**Comment by OGKevin** [comment]
Please create issue in bunq/tinker_python to add script to retrieve joint accounts. Tinker will be used as example. 

You must load your ApiContext in bunqContext and then preform a call to the joint account class. Please see the documented code and/or method signature on how to use the methods.
