### ISSUE TITLE
Update samples and readme

### ISSUE THREAD

**Issue by CharlPels** [bunq/sdk_python#93]
## Steps to reproduce:
1. Samples seem not to work anymore

## What should happen:
1. Rework on documentation en sample code.

## What happens:
1. Spending hours on code that is not working anymore, sdk will break your old code.

## Traceback
[//]: # (If there is a traceback please share it in a quote! You can do this by pasting the traceback text, highlighting it and pressing the quote button.)

## SDK version and environment
- Tested on [0.12.4](https://github.com/bunq/sdk_python/releases/tag/0.12.4)
- [ ] Sandbox
- [ ] Production

## Response id
[//]: # (If this error has something to do with a request that fails, please provide the response id of the request.)
- Response id:

## Extra info:
[//]: # (Please provide any other relevant information here)

**Comment by OGKevin** [comment]
Closing in favour of #84 and #87
