### ISSUE TITLE
Bunq sdk release request

### ISSUE THREAD

**Issue by CharlPels** [bunq/sdk_python#97]
## Steps to reproduce:
1. None

## What should happen:
1. A new release of the sdk

## What happens:
1. Currently in the 13.0 version there is no support for joined accounts the soltion for that seems to be availeble but would need a nieuwe release i guess.

## Traceback
[//]: # (If there is a traceback please share it in a quote! You can do this by pasting the traceback text, highlighting it and pressing the quote button.)

## SDK version and environment
- Tested on [0.12.4](https://github.com/bunq/sdk_python/releases/tag/0.12.4)
- [ ] Sandbox
- [ ] Production

## Response id
[//]: # (If this error has something to do with a request that fails, please provide the response id of the request.)
- Response id:

## Extra info:
[//]: # (Please provide any other relevant information here)

**Comment by OGKevin** [comment]
@CharlPels Until version 1.0.0 (which will be the next release) All the SDK's will be released at the same time. After 1.0.0 it will be easier to dynamically make releases independent of the other SDK's.

As this issue has already been fixed on develop, i would advice you to temporary pip install the following commit: 0a793d9c12f2d2237a930466d284fd81a4df33bc.

You can do that as explained here: https://stackoverflow.com/questions/13685920/install-specific-git-commit-with-pip

**Comment by CharlPels** [comment]
Kevin,

I even did a 
python -m pip install git+git://github.com/bunq/sdk_python.git

Requirement already satisfied: certifi>=2017.4.17 in d:\home\python362x64\lib\site-packages (from requests==2.18.1->bunq-sdk==0.13.1) (2018.1.18)
Installing collected packages: bunq-sdk
  Found existing installation: bunq-sdk 0.13.0
    Uninstalling bunq-sdk-0.13.0:
      Successfully uninstalled bunq-sdk-0.13.0
  Running setup.py install for bunq-sdk: started
    Running setup.py install for bunq-sdk: finished with status 'done'
Successfully installed bunq-sdk-0.13.1

That works oke but still no joined accounts

oohh this one also tested and no luck on the joined accounts part.
python -m pip install git+git://github.com/bunq/sdk_python.git@0a793d9c12f2d2237a930466d284fd81a4df33bc


code for getting the .MonetaryAccount is
    pagination = Pagination()
    pagination.count = 80

    all_monetary_account_bank = endpoint.MonetaryAccountBank.list(
            pagination.url_params_count_only).value

**Comment by OGKevin** [comment]
what does `oohh this one also tested and no luck on the joined accounts part.` mean ? What error are you getting etc etc. Commit 0a793d9c12f2d2237a930466d284fd81a4df33bc fixed the bug causing joint accounts not to be retrieved. After java and c# SDK's are finished a stable release will be made.

**Comment by CharlPels** [comment]
I am not getting errors al is working oke only still no joined accounts

**Comment by OGKevin** [comment]
How do you know/determine/come to the conclusion  that `still no joined accounts` ? 


Next release won't change anything if you've installed the comment mentioned above correctly. I really dont understand what you mean with no joined accounts :(. Do you have a joint account can you see it in the app ?

**Comment by CharlPels** [comment]
Kevin,

I am now running 0.13.1 

To be shure Successfully installed bunq-sdk-0.13.1
and don’t see my joined or as thay are called in the bunq app co-owner accounts, and yes i do have them and is used for most of my bills so I am shure it is there.

**Comment by OGKevin** [comment]
@CharlPels `0.13.1` does NOT have support for joint accounts due to a bug which has been fixed on the develop branch. 

I've ran `pip install git+git://github.com/bunq/sdk_python.git@0a793d9` and could see indeed that the fix was there. 

```
all_monetary_account_bank = endpoint.MonetaryAccountBank.list(
        pagination.url_params_count_only).value
```

will ONLY return `MonteryAccountBank` and not `MonetaryAccountJoint` these are 2 different account types.

**Comment by CharlPels** [comment]
Kevin,

Thanks for the info, it works, the MonetaryAccountJoint was the main issue, I now see all accounts, thanks
